# Generated by Django 3.2.14 on 2022-12-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('studentbranch', models.CharField(max_length=100)),
                ('student_univ', models.CharField(max_length=100)),
            ],
        ),
    ]
