# Generated by Django 3.2.14 on 2023-01-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentbranch',
            new_name='student_branch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentname',
            new_name='student_name',
        ),
    ]
