# Generated by Django 3.2.14 on 2022-12-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyMembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='profile_image',
            field=models.FileField(default=None, null=True, upload_to='profileimage'),
        ),
    ]
