# Generated by Django 3.2.14 on 2022-12-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyMembers', '0002_familymembers_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=13)),
                ('work', models.CharField(max_length=50)),
                ('income', models.FloatField()),
                ('profile_image', models.FileField(default=None, null=True, upload_to='static/profileimages')),
                ('pay_slip', models.FileField(default=None, null=True, upload_to='static/payslips')),
            ],
        ),
        migrations.DeleteModel(
            name='FamilyMembers',
        ),
    ]
